import {
  Code,
  Database,
  Palette,
  Cloud,
} from "lucide-react"
export default function CourseData(){
    const courseCategories = [
      {
        id: "software-dev",
        name: "Software Development",
        icon: Code,
        gradient: "from-purple-500 via-purple-600 to-purple-700",
        description: "Master modern programming languages and frameworks",
      },
      {
        id: "data",
        name: "Data",
        icon: Database,
        gradient: "from-purple-400 via-purple-500 to-purple-600",
        description: "Analyze data and build intelligent systems",
      },
      {
        id: "design",
        name: "Design",
        icon: Palette,
        gradient: "from-purple-300 via-purple-400 to-purple-500",
        description: "Create beautiful and functional user experiences",
      },
      {
        id: "cloud",
        name: "Cloud Computing",
        icon: Cloud,
        gradient: "from-purple-600 via-purple-700 to-black",
        description: "Deploy and scale applications in the cloud",
      },
    ]
    
    const allCourses = [
      {
        id: "data-science",
        title: "Data Science Immersive",
        category: "data",
        level: "Beginner",
        duration: "8 weeks",
        students: 13450,
        rating: 4.8,
        price: 5000,
        instructor: "Michael Brown",
        description: "This comprehensive program covers everything from Python programming to advanced machine learning algorithms. Gain hands-on experience with real datasets and build a portfolio of data science projects.",
        image: "/images/data-science.jpeg",
        skills: ["Python", "scikit", "numpy", "pandas", "Matplotlib"],
        featured: true,
        gradient: "from-purple-500 via-purple-700 to-black",
      },
      {
        id: "business-intelligence",
        title: "Business Intelligence",
        category: "data",
        level: "beginner",
        duration: "10 weeks",
        students: 100,
        rating: 4.9,
        price: 5000,
        instructor: "Oladosu Ibrahim",
        description: "Master the tools and techniques to transform raw data into strategic insights. Learn Excel, SQL, Power BI, and Tableau to create compelling visualizations and dashboards that drive business decisions.",
        image: "/images/business-analysis.jpeg",
        skills: ["EXCEL", "SQl", "POWER BI", "TABLEAU"],
        featured: false,
        gradient: "from-purple-400 via-purple-500 to-purple-600",
      },
      {
        id: "data-engineering",
        title: "Data Engineering Bootcamp",
        category: "data",
        level: "Beginner",
        duration: "8 weeks",
        students: 14200,
        rating: 4.6,
        price: 5000,
        instructor: "John .A",
        description: "Master the skills to design, build, and maintain the data infrastructure that powers modern organizations. This hands-on program covers everything from large-scale data pipelines to cloud deployment on Azure, AWS, and Microsoft Fabric, with practical experience in relational/NoSQL databases, Apache Beam, and DBT.",
        image: "/images/data-engineering.jpeg",
        skills: ["Apache Beam","DBT", "SQL/NoSQL", "Azure", "AWS", "Data Pipelines", "Data Warehousing", "Microsoft Fabric"],
        featured: false,
        gradient: "from-purple-200 via-purple-300 to-purple-400",
      },
      {
        id: "fullstack-development",
        title: "Full Stack JavaScript",
        category: "software-dev",
        level: "Advanced",
        duration: "24 weeks",
        students: 8920,
        rating: 4.9,
        price: 5000,
        instructor: "Elena Rodriguez",
        description: "Complete full stack development with modern JavaScript",
        image: "/images/fullstack-dev.jpeg",
        skills: ["React", "Node.js", "MongoDB", "GraphQL"],
        featured: true,
        gradient: "from-purple-600 via-purple-700 to-black",
      },
      {
        id: "data-analysis",
        title: "Data Analysis with Python",
        category: "data",
        level: "Beginner",
        duration: "8 weeks",
        students: 14200,
        rating: 4.6,
        price: 5000,
        instructor: "James Miller",
        description: "Learn the essential skills needed to analyze and interpret data effectively. Master Excel, SQL, and basic Python for data manipulation, visualization, and reporting across various business contexts.",
        image: "/images/data-analysis.jpeg",
        skills: ["Excel", "Power Bi", "Tableau", "SQL"],
        featured: false,
        gradient: "from-purple-200 via-purple-300 to-purple-400",
      },
    ]
    return{
        allCourses,
        courseCategories
    }
}