import {
  Code,
  Database,
  Palette,
  Cloud,
} from "lucide-react"
export default function CourseData(){
    const courseCategories = [
      {
        id: "software-dev",
        name: "Software Development",
        icon: Code,
        gradient: "from-purple-500 via-purple-600 to-purple-700",
        description: "Master modern programming languages and frameworks",
      },
      {
        id: "data",
        name: "Data Science",
        icon: Database,
        gradient: "from-purple-400 via-purple-500 to-purple-600",
        description: "Analyze data and build intelligent systems",
      },
      {
        id: "design",
        name: "Design",
        icon: Palette,
        gradient: "from-purple-300 via-purple-400 to-purple-500",
        description: "Create beautiful and functional user experiences",
      },
      {
        id: "cloud",
        name: "Cloud Computing",
        icon: Cloud,
        gradient: "from-purple-600 via-purple-700 to-black",
        description: "Deploy and scale applications in the cloud",
      },
    ]
    
    const allCourses = [
      {
        id: "react-fundamentals",
        title: "React Fundamentals",
        category: "software-dev",
        level: "Beginner",
        duration: "8 weeks",
        students: 15420,
        rating: 4.9,
        price: 99,
        instructor: "Sarah Chen",
        description: "Learn React from scratch and build modern web applications",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["React", "JSX", "Components", "State Management"],
        featured: true,
        gradient: "from-purple-500 via-purple-600 to-purple-700",
      },
      {
        id: "nodejs-backend",
        title: "Node.js Backend Development",
        category: "software-dev",
        level: "Intermediate",
        duration: "10 weeks",
        students: 12350,
        rating: 4.8,
        price: 129,
        instructor: "Marcus Johnson",
        description: "Build scalable backend applications with Node.js and Express",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Node.js", "Express", "MongoDB", "REST APIs"],
        featured: false,
        gradient: "from-purple-400 via-purple-500 to-purple-600",
      },
      {
        id: "fullstack-javascript",
        title: "Full Stack JavaScript",
        category: "software-dev",
        level: "Advanced",
        duration: "16 weeks",
        students: 8920,
        rating: 4.9,
        price: 199,
        instructor: "Elena Rodriguez",
        description: "Complete full stack development with modern JavaScript",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["React", "Node.js", "MongoDB", "GraphQL"],
        featured: true,
        gradient: "from-purple-600 via-purple-700 to-black",
      },
      {
        id: "python-programming",
        title: "Python Programming Mastery",
        category: "software-dev",
        level: "Beginner",
        duration: "12 weeks",
        students: 18750,
        rating: 4.7,
        price: 89,
        instructor: "David Kim",
        description: "Master Python programming from basics to advanced concepts",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Python", "OOP", "Data Structures", "Algorithms"],
        featured: false,
        gradient: "from-purple-300 via-purple-400 to-purple-500",
      },
      {
        id: "machine-learning",
        title: "Machine Learning Fundamentals",
        category: "data",
        level: "Intermediate",
        duration: "14 weeks",
        students: 9840,
        rating: 4.8,
        price: 149,
        instructor: "Dr. Lisa Wang",
        description: "Learn machine learning algorithms and build predictive models",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Python", "Scikit-learn", "TensorFlow", "Statistics"],
        featured: true,
        gradient: "from-purple-400 via-purple-600 to-black",
      },
      {
        id: "data-analysis",
        title: "Data Analysis with Python",
        category: "data",
        level: "Beginner",
        duration: "8 weeks",
        students: 14200,
        rating: 4.6,
        price: 79,
        instructor: "James Miller",
        description: "Analyze and visualize data using Python and pandas",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Python", "Pandas", "NumPy", "Matplotlib"],
        featured: false,
        gradient: "from-purple-200 via-purple-300 to-purple-400",
      },
      {
        id: "aws-fundamentals",
        title: "AWS Cloud Fundamentals",
        category: "cloud",
        level: "Beginner",
        duration: "10 weeks",
        students: 13450,
        rating: 4.8,
        price: 119,
        instructor: "Michael Brown",
        description: "Learn Amazon Web Services from basics to deployment",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["AWS", "EC2", "S3", "Lambda"],
        featured: true,
        gradient: "from-purple-500 via-purple-700 to-black",
      },
      {
        id: "figma-design",
        title: "UI/UX Design with Figma",
        category: "design",
        level: "Beginner",
        duration: "6 weeks",
        students: 11200,
        rating: 4.8,
        price: 69,
        instructor: "Sophie Anderson",
        description: "Create stunning user interfaces and experiences with Figma",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Figma", "UI Design", "UX Research", "Prototyping"],
        featured: false,
        gradient: "from-purple-300 via-purple-500 to-purple-700",
      },
    ]
    return{
        allCourses,
        courseCategories
    }
}