export default function CourseInfo(){
    // Bootcamp course data
    const courseData = {
      "react-fundamentals": {
        id: "react-fundamentals",
        title: "React Development Bootcamp",
        subtitle: "Intensive 8-Week Program to Master Modern React",
        category: "Software Development",
        level: "Beginner to Advanced",
        duration: "8 weeks",
        schedule: "Mon-Wed-Fri, 6:00 PM - 9:00 PM",
        nextCohort: "March 15, 2024",
        students: 15420,
        price: 2499,
        originalPrice: 3499,
        bootcampType: "Part-time Evening",
        instructor: {
          name: "Sarah Chen",
          title: "Senior Frontend Developer at Google",
          avatar: "/placeholder.svg?height=120&width=120",
          bio: "Sarah has 8+ years of experience building scalable web applications at top tech companies. She's mentored over 500 developers and specializes in React ecosystem and modern frontend architecture.",
          courses: 12,
          experience: "8+ years",
          companies: ["Google", "Meta", "Netflix"],
        },
        description:
          "Transform into a React expert through our intensive bootcamp program. This comprehensive 8-week journey combines theoretical knowledge with hands-on projects, mentorship, and career support to prepare you for senior frontend roles.",
        image: "/placeholder.svg?height=500&width=800",
        gradient: "from-purple-500 via-purple-600 to-purple-700",
        skills: ["React 18", "TypeScript", "Next.js", "State Management", "Testing", "Performance"],
        prerequisites: [
          "Solid understanding of JavaScript ES6+",
          "Basic knowledge of HTML5 and CSS3",
          "Familiarity with Git version control",
          "Understanding of web development fundamentals",
        ],
        learningOutcomes: [
          "Build production-ready React applications from scratch",
          "Master advanced React patterns and performance optimization",
          "Implement complex state management with Redux and Zustand",
          "Create responsive, accessible user interfaces",
          "Write comprehensive tests for React components",
          "Deploy applications to modern cloud platforms",
          "Collaborate effectively using Git and GitHub workflows",
          "Prepare for senior frontend developer interviews",
        ],
        curriculum: [
          {
            week: 1,
            title: "React Foundations & Modern JavaScript",
            focus: "Building Strong Fundamentals",
            topics: [
              "ES6+ JavaScript deep dive",
              "React components and JSX mastery",
              "Props, state, and event handling",
              "Component lifecycle and hooks introduction",
            ],
            projects: ["Personal Portfolio Component", "Interactive Todo App"],
            duration: "9 hours",
          },
          {
            week: 2,
            title: "Advanced Hooks & State Management",
            focus: "Mastering React Hooks",
            topics: [
              "useState and useEffect deep dive",
              "Custom hooks development",
              "useContext for state sharing",
              "useReducer for complex state logic",
            ],
            projects: ["Weather Dashboard", "Shopping Cart System"],
            duration: "9 hours",
          },
          {
            week: 3,
            title: "Routing & Navigation",
            focus: "Single Page Applications",
            topics: [
              "React Router v6 implementation",
              "Dynamic routing and parameters",
              "Protected routes and authentication",
              "Code splitting and lazy loading",
            ],
            projects: ["Multi-page Blog Platform", "User Authentication System"],
            duration: "9 hours",
          },
          {
            week: 4,
            title: "Forms & Data Handling",
            focus: "User Input & API Integration",
            topics: [
              "Controlled vs uncontrolled components",
              "Form validation and error handling",
              "API integration with fetch and axios",
              "Loading states and error boundaries",
            ],
            projects: ["Contact Management System", "Real-time Chat Interface"],
            duration: "9 hours",
          },
          {
            week: 5,
            title: "Advanced State Management",
            focus: "Scalable Application Architecture",
            topics: [
              "Redux Toolkit implementation",
              "Zustand for lightweight state",
              "Context API best practices",
              "State normalization patterns",
            ],
            projects: ["E-commerce Application", "Task Management Dashboard"],
            duration: "9 hours",
          },
          {
            week: 6,
            title: "Testing & Quality Assurance",
            focus: "Professional Development Practices",
            topics: [
              "Jest and React Testing Library",
              "Unit and integration testing",
              "Test-driven development (TDD)",
              "End-to-end testing with Cypress",
            ],
            projects: ["Comprehensive Test Suite", "CI/CD Pipeline Setup"],
            duration: "9 hours",
          },
          {
            week: 7,
            title: "Performance & Optimization",
            focus: "Production-Ready Applications",
            topics: [
              "React.memo and useMemo optimization",
              "Code splitting and bundle analysis",
              "Performance monitoring and debugging",
              "Accessibility and SEO best practices",
            ],
            projects: ["Performance-Optimized App", "Accessibility Audit"],
            duration: "9 hours",
          },
          {
            week: 8,
            title: "Capstone Project & Career Prep",
            focus: "Portfolio Development",
            topics: [
              "Full-stack application development",
              "Deployment and DevOps basics",
              "Code review and collaboration",
              "Interview preparation and portfolio review",
            ],
            projects: ["Full-Stack Capstone Project", "Portfolio Website"],
            duration: "9 hours",
          },
        ],
        features: [
          "72 hours of live instruction",
          "8 hands-on projects",
          "1-on-1 mentorship sessions",
          "Career services and job placement",
          "Lifetime access to materials",
          "Industry-standard tools and workflows",
          "Peer collaboration and networking",
          "Certificate of completion",
        ],
        careerSupport: [
          "Resume and portfolio review",
          "Mock technical interviews",
          "Job search strategy sessions",
          "Industry networking events",
          "Salary negotiation guidance",
          "6 months post-graduation support",
        ],
        jobOutcomes: {
          placementRate: 94,
          averageSalary: 85000,
          timeToJob: 3.2,
          topCompanies: ["Google", "Meta", "Amazon", "Netflix", "Spotify", "Airbnb"],
        },
      },
      // Add more bootcamp courses...
    }
    
    return{
        courseData
    }
}